global:
  resolve_timeout: 5m

route:
  receiver: 'telegram'
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 30m

receivers:
  - name: 'telegram'
    telegram_configs:
      - bot_token: '8078884169:AAEZh-l8x29D5sssvAv3AZkSFGKL_wH__VM'
        chat_id: '1990942304'
        parse_mode: 'Markdown'
        message: |
           *{{ .Status | toUpper }}*: {{ .CommonLabels.alertname }}
           *{{ .CommonLabels.instance }}*
           {{ .CommonAnnotations.description }}
           Время: {{ .StartsAt }}
